- name: setup virtualenv
  pip: virtualenv={{virtualenv_path}} requirements={{virtualenv_path}}/requirements.txt

- name: Django sycdb
  django_manage: command=syncdb app_path={{virtualenv_path}}/vagranttest virtualenv={{virtualenv_path}}

- name: Django migrate
  django_manage: command=migrate app_path={{virtualenv_path}}/vagranttest virtualenv={{virtualenv_path}}