- name: Install packages
  sudo: yes
  apt: pkg={{item}} state=installed update_cache=yes
  with_items:
    # database
    - postgresql
    - python-psycopg2
    - libpq-dev

    # python
    - python-dev
    - python-setuptools
    - python-virtualenv

- name: Allow passwords authentication for local socket users
  sudo: yes
  copy: src=pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf
  notify:
    Restart Postgres

- name: Create database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{db_name}}

- name: Create user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{db_user}} password={{db_pass}} state=present role_attr_flags=NOSUPERUSER,CREATEDB

- name: Provide user with DB permissions
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{db_user}} db={{db_name}} priv=ALL